[package]
  cjc-version = "1.0.0"
  name = "commandline_spinner_demo"
  description = "Spinner demo for commandline"
  version = "0.0.1"
  output-type = "executable"
  compile-option = "--debug-macro -Woff unused"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  commandline = { path = "../.." }
